/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhanvien;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.util.Calendar;

/**
 *
 * @author THI
 */
public class DongHoPanel extends javax.swing.JPanel  
implements Runnable
{
    private Thread t;
    public DongHoPanel() {
        initComponents();
        t =new Thread(this);
        t.start();
    }
   
  public void paint(Graphics g) {
    super.paint(g);
    Font f = new Font("Arial", Font.BOLD, 16);
    g.setFont(f);
    g.setColor(Color.RED);
    Calendar d = Calendar.getInstance();
    int ngay = d.get(Calendar.DAY_OF_MONTH);
    int thang = d.get(Calendar.MONTH)+1;
    int nam = d.get(Calendar.YEAR);
    int gio = d.get(Calendar.HOUR_OF_DAY);
    int phut = d.get(Calendar.MINUTE);
    int giay = d.get(Calendar.SECOND);
    g.drawString(ngay +"/"+thang+"/"+nam+" "+
        gio + ":" + phut + ":" + giay, this.getWidth() - 200, this.getHeight() - 10 );
  }

  public void run() {
    while (true) {
      repaint();    //gọi hàm paint
      try {
        Thread.sleep(1000);
      }
      catch (InterruptedException e) {}
    }
  }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
