/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhanvien;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vi Vi
 */
public class GiaoDienNhanVien extends javax.swing.JInternalFrame {
       DSNV ds = new DSNV();
       DefaultTableModel dm= new DefaultTableModel();
       ArrayList<NhanVien> m = new ArrayList<NhanVien>();
    /**
     * Creates new form GiaoDienNhanVien
     */
    public GiaoDienNhanVien() {
        super(" CẬP NHẬT NHÂN VIÊN ",true,true,true,true);
        initComponents();
            
        this.jTable1.setModel(dm);
 String[] tenCot={"Mã", "Họ tên","Hệ số lương","Ngày vào làm",
     "Phái","Công việc","Chức vụ","Phụ cấp chức vụ "};
        dm.setColumnIdentifiers(tenCot);
        this.rbnam.setSelected(true);
        this.rbchuyenvien.setSelected(true);
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        bthem = new javax.swing.JButton();
        bsua = new javax.swing.JButton();
        bthoat = new javax.swing.JButton();
        bhienthi = new javax.swing.JButton();
        bxoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfcongviec = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfhoten = new javax.swing.JTextField();
        tfma = new javax.swing.JTextField();
        tfhsl = new javax.swing.JTextField();
        tfngayvao = new javax.swing.JTextField();
        rbnam = new javax.swing.JRadioButton();
        rbnu = new javax.swing.JRadioButton();
        rbcbql = new javax.swing.JRadioButton();
        rbchuyenvien = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btimhoten = new javax.swing.JButton();
        btimma = new javax.swing.JButton();
        btimmax = new javax.swing.JButton();
        btimphai = new javax.swing.JButton();
        bxoama = new javax.swing.JButton();
        bxoadong = new javax.swing.JButton();
        btrungbinh = new javax.swing.JButton();
        bxoahoten = new javax.swing.JButton();
        dongHoPanel1 = new nhanvien.DongHoPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfchucvu = new javax.swing.JTextField();
        tfpccv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/if_Add_131846.png"))); // NOI18N
        bthem.setText("THÊM");
        bthem.setToolTipText("THÊM");
        bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemActionPerformed(evt);
            }
        });

        bsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/if_Settings_131786.png"))); // NOI18N
        bsua.setText("SỬA");
        bsua.setToolTipText("SỬA");
        bsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuaActionPerformed(evt);
            }
        });

        bthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/if_Exit_131885.png"))); // NOI18N
        bthoat.setText("THOÁT");
        bthoat.setToolTipText("THOÁT");
        bthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthoatActionPerformed(evt);
            }
        });

        bhienthi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/if_Preview_131689.png"))); // NOI18N
        bhienthi.setText("HIỆN THỊ");
        bhienthi.setToolTipText("HIỆN THỊ");
        bhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhienthiActionPerformed(evt);
            }
        });

        bxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/if_Erase_131842.png"))); // NOI18N
        bxoa.setText("XÓA");
        bxoa.setToolTipText("XÓA");
        bxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bhienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bthoat)
                            .addComponent(bxoa))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bhienthi, bsua, bthem, bthoat, bxoa});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bthem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bhienthi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(bsua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bxoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bthoat)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bhienthi, bsua, bthem, bthoat, bxoa});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Chuyên viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("CÔNG VIỆC");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfcongviec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcongviecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcongviec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("MÃ NHÂN VIÊN");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("HỌ TÊN");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("HỆ SỐ LƯƠNG");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("NGÀY VÀO LÀM");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("PHÁI");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnam);
        rbnam.setText("Nam");

        buttonGroup1.add(rbnu);
        rbnu.setText("Nữ");

        buttonGroup2.add(rbcbql);
        rbcbql.setText("Cán bộ quản lý");
        rbcbql.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbcbqlItemStateChanged(evt);
            }
        });

        buttonGroup2.add(rbchuyenvien);
        rbchuyenvien.setText("Chuyên viên");
        rbchuyenvien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbchuyenvienItemStateChanged(evt);
            }
        });
        rbchuyenvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbchuyenvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbchuyenvien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbcbql))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfhoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfhsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfngayvao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(rbnam, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbnu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfhoten, tfhsl, tfma, tfngayvao});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfhoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfhsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfngayvao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbnam)
                    .addComponent(rbnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbchuyenvien)
                    .addComponent(rbcbql))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, tfhoten, tfhsl, tfma, tfngayvao});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DANH SÁCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btimhoten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btimhoten.setText("TÌM HỌ TÊN");
        btimhoten.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btimhoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimhotenActionPerformed(evt);
            }
        });

        btimma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btimma.setText("TÌM MÃ");
        btimma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btimma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimmaActionPerformed(evt);
            }
        });

        btimmax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btimmax.setText("TÌM MAX LƯƠNG");
        btimmax.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btimmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimmaxActionPerformed(evt);
            }
        });

        btimphai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btimphai.setText("TÌM PHÁI");
        btimphai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btimphai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimphaiActionPerformed(evt);
            }
        });

        bxoama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bxoama.setText("XÓA MÃ");
        bxoama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bxoama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoamaActionPerformed(evt);
            }
        });

        bxoadong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bxoadong.setText("XÓA DÒNG");
        bxoadong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bxoadong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoadongActionPerformed(evt);
            }
        });

        btrungbinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btrungbinh.setText("TRUNG BÌNH LƯƠNG");
        btrungbinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btrungbinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrungbinhActionPerformed(evt);
            }
        });

        bxoahoten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bxoahoten.setText("XÓA HỌ TÊN");
        bxoahoten.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bxoahoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoahotenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btimphai, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btimma, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btimhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bxoadong, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bxoama, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bxoahoten, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btimmax, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btrungbinh, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btimma)
                    .addComponent(btimhoten)
                    .addComponent(btimmax)
                    .addComponent(bxoadong)
                    .addComponent(bxoama)
                    .addComponent(bxoahoten)
                    .addComponent(btrungbinh)
                    .addComponent(btimphai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btimhoten, btimma, btimmax, btimphai, btrungbinh, bxoadong, bxoahoten, bxoama});

        javax.swing.GroupLayout dongHoPanel1Layout = new javax.swing.GroupLayout(dongHoPanel1);
        dongHoPanel1.setLayout(dongHoPanel1Layout);
        dongHoPanel1Layout.setHorizontalGroup(
            dongHoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        dongHoPanel1Layout.setVerticalGroup(
            dongHoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Cán bộ quản lý", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("PHỤC CẤP CHỨC VỤ");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfchucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfchucvuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("CHỨC VỤ");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfpccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfchucvu, tfpccv});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfpccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dongHoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dongHoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btimmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimmaxActionPerformed
 JOptionPane.showMessageDialog(this," Nhân viên có lương cao nhất "+ds.timMaxLuong());    }//GEN-LAST:event_btimmaxActionPerformed

    private void bhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhienthiActionPerformed

     JOptionPane.showMessageDialog(this,"Danh sách nhân viên "+ds.hienThi());
    
    }//GEN-LAST:event_bhienthiActionPerformed

    private void btrungbinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrungbinhActionPerformed
     JOptionPane.showMessageDialog(this," trung bình lương : "+ds.trungBinhLuong());
    }//GEN-LAST:event_btrungbinhActionPerformed

    private void btimmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimmaActionPerformed
        String n = JOptionPane.showInputDialog(null, "Nhập mã");
        JOptionPane.showMessageDialog(this,"  nhân viên có mã chỉ định tìm được: "+ds.timMa(n));
    }//GEN-LAST:event_btimmaActionPerformed

    private void btimphaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimphaiActionPerformed
      if(this.rbnam.isSelected())
         JOptionPane.showMessageDialog(this,ds.timPhai(true));
      else  JOptionPane.showMessageDialog(this,ds.timPhai(false));
    }//GEN-LAST:event_btimphaiActionPerformed

    private void bthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemActionPerformed
       
           
       String ma =this.tfma.getText();
       String ht = this.tfhoten.getText();
       double hsl=Double.parseDouble(this.tfhsl.getText());
       DateFormat df = new SimpleDateFormat("yyyy/M/d");
       Date nvl = new Date ();
           try {
               nvl=df.parse(this.tfngayvao.getText());
           } catch (ParseException ex){ }
           boolean phai =true;
           if(this.rbnu.isSelected()) phai =false;
           NhanVien v;
           if(this.rbchuyenvien.isSelected()){
               String cv=this.tfcongviec.getText();
               v = new ChuyenVien(cv,ma,ht,hsl,nvl,phai);
               ds.them(v);
               dm.addRow(new Object [] {v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),v.getNgayVaoLam(),
                   v.isPhai(),((ChuyenVien)v).getCongViec()});
           }
           else { String cv=this.tfchucvu.getText();
                    double pccv= Double.parseDouble(this.tfpccv.getText());
                    v = new CanBoQuanLy(cv,pccv,ma,ht,hsl,nvl,phai);
                    ds.them(v);
                    dm.addRow(new Object [] {v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),v.getNgayVaoLam(),
                   v.isPhai(),"",((CanBoQuanLy)v).getChucVu(),((CanBoQuanLy)v).getPhuCapChucVu()});
                    
           }
    }//GEN-LAST:event_bthemActionPerformed

    private void bxoamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoamaActionPerformed
        String n = JOptionPane.showInputDialog(null, "Nhập mã");
        int i=ds.xoa(n);
        if(i!=-1)
            dm.removeRow(i);
    }//GEN-LAST:event_bxoamaActionPerformed

    private void btimhotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimhotenActionPerformed
         String n = JOptionPane.showInputDialog(null, "Nhập họ tên");
        JOptionPane.showMessageDialog(this," họ tên tìm được "+ds.timHoTen(n));
    }//GEN-LAST:event_btimhotenActionPerformed

    private void bsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuaActionPerformed
        int j = ds.timmanv(this.tfma.getText());
       if(j!=-1)
       {
        String ma =this.tfma.getText();
       String ht = this.tfhoten.getText();
       double hsl=Double.parseDouble(this.tfhsl.getText());
       DateFormat df = new SimpleDateFormat("yyyy/M/d");
       Date nvl = new Date ();
           try {
               nvl=df.parse(this.tfngayvao.getText());
           } catch (ParseException ex){ }
           boolean phai =true;
           if(this.rbnu.isSelected()) phai =false;
           NhanVien v;
           if(this.rbchuyenvien.isSelected()){
               String cv=this.tfcongviec.getText();
               v = new ChuyenVien(cv,ma,ht,hsl,nvl,phai);
              //int i = this.jTable1.getSelectedRow();
                    ds.sua(j, v);
                    dm.removeRow(j);
               dm.insertRow(j,new Object [] {v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),v.getNgayVaoLam(),
                   v.isPhai(),((ChuyenVien)v).getCongViec()});
           }
           else { String cv=this.tfchucvu.getText();
                    double pccv= Double.parseDouble(this.tfpccv.getText());
                    v = new CanBoQuanLy(cv,pccv,ma,ht,hsl,nvl,phai);
                    //int i = this.jTable1.getSelectedRow();
                    ds.sua(j, v);
                    dm.removeRow(j);
                    dm.insertRow(j,new Object [] {v.getMaNV(),v.getHoTen(),v.getHeSoLuong(),v.getNgayVaoLam(),
                   v.isPhai(),"",((CanBoQuanLy)v).getChucVu(),((CanBoQuanLy)v).getPhuCapChucVu()});
                    
           }
       }
       return;
    }//GEN-LAST:event_bsuaActionPerformed

    private void bxoadongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoadongActionPerformed

        int n = JOptionPane.showConfirmDialog(this, "Chắc chắn xóa không?", "xóa", JOptionPane.YES_NO_OPTION);
       if(n==JOptionPane.NO_OPTION) return;
        
        int i = this.jTable1.getSelectedRow();
        if(i>=0 && i<this.jTable1.getRowCount())
        { ds.xoaViTri(i);
          dm.removeRow(i);
      
        }
    }//GEN-LAST:event_bxoadongActionPerformed

    private void bthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthoatActionPerformed
       int n = JOptionPane.showConfirmDialog(this, "Chắc chắn thoát không?", "thoát", JOptionPane.YES_NO_OPTION);
       if(n==JOptionPane.YES_OPTION) 
        this.dispose();
       return;
    }//GEN-LAST:event_bthoatActionPerformed

    private void rbchuyenvienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbchuyenvienItemStateChanged
this.tfpccv.setEnabled(false);
        this.tfchucvu.setEnabled(false);
        this.tfcongviec.setEnabled(true);
            }//GEN-LAST:event_rbchuyenvienItemStateChanged

    private void rbcbqlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbcbqlItemStateChanged
        this.tfpccv.setEnabled(true);
        this.tfchucvu.setEnabled(true);
        this.tfcongviec.setEnabled(false);
    }//GEN-LAST:event_rbcbqlItemStateChanged

    private void bxoahotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoahotenActionPerformed
     String n = JOptionPane.showInputDialog(null, "Nhập họ tên");
        int i=ds.xoaHoTen(n);
        if(i!=-1)
            dm.removeRow(i);
    }//GEN-LAST:event_bxoahotenActionPerformed

    private void bxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoaActionPerformed
        // TODO add your handling code here:
        this.tfma.setText(" ");
        this.tfhoten.setText(" ");
        this.tfhsl.setText(" ");
        this.tfngayvao.setText(" ");
        this.tfcongviec.setText(" ");
        this.tfchucvu.setText(" ");
        this.tfpccv.setText(" ");
    }//GEN-LAST:event_bxoaActionPerformed

    private void tfcongviecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcongviecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcongviecActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void rbchuyenvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbchuyenvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbchuyenvienActionPerformed

    private void tfchucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfchucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfchucvuActionPerformed

    private void tfmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhienthi;
    private javax.swing.JButton bsua;
    private javax.swing.JButton bthem;
    private javax.swing.JButton bthoat;
    private javax.swing.JButton btimhoten;
    private javax.swing.JButton btimma;
    private javax.swing.JButton btimmax;
    private javax.swing.JButton btimphai;
    private javax.swing.JButton btrungbinh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton bxoa;
    private javax.swing.JButton bxoadong;
    private javax.swing.JButton bxoahoten;
    private javax.swing.JButton bxoama;
    private nhanvien.DongHoPanel dongHoPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbcbql;
    private javax.swing.JRadioButton rbchuyenvien;
    private javax.swing.JRadioButton rbnam;
    private javax.swing.JRadioButton rbnu;
    private javax.swing.JTextField tfchucvu;
    private javax.swing.JTextField tfcongviec;
    private javax.swing.JTextField tfhoten;
    private javax.swing.JTextField tfhsl;
    private javax.swing.JTextField tfma;
    private javax.swing.JTextField tfngayvao;
    private javax.swing.JTextField tfpccv;
    // End of variables declaration//GEN-END:variables
}
